/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_loadimagenative_Native */

#ifndef _Included_com_example_loadimagenative_Native
#define _Included_com_example_loadimagenative_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_loadimagenative_Native
 * Method:    initCamera
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_loadimagenative_Native_initCamera
  (JNIEnv *, jclass);

/*
 * Class:     com_example_loadimagenative_Native
 * Method:    getBytes
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_example_loadimagenative_Native_getBytes
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_example_loadimagenative_Native
 * Method:    initCascade
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_loadimagenative_Native_initCascade
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
